import { hmacHex } from "./auth-v2.server";
export type RateLimitScope = "join" | "resume" | "recovery" | "create_pair" | "upload" | "calendar";
export type RateLimitRequest = { scope: RateLimitScope; key: string; limit: number; windowSeconds: number };
export type RateLimitResult = { allowed: boolean; count: number; remaining: number; retryAfterSeconds: number };
export function rateLimitKeyMaterial(scope: RateLimitScope, key: string): string { return `ratelimit:${scope}:${key}`; }
export async function rateLimitKeyHash(scope: RateLimitScope, key: string): Promise<string> { return hmacHex(rateLimitKeyMaterial(scope, key)); }
export const RATE_LIMIT_MAX_WINDOW_SECONDS = 31_536_000;
const RATE_LIMIT_SCOPES: readonly RateLimitScope[] = ["join", "resume", "recovery", "create_pair", "upload", "calendar"];
function isPositiveInt(value: unknown, min: number): value is number { return typeof value === "number" && Number.isInteger(value) && value >= min; }
function invalidArgs(what: string): never { throw new Error(`rate limit: invalid ${what}`); }
export function assertRateLimitBounds(limit: unknown, windowSeconds: unknown): void { if (!isPositiveInt(limit, 1)) invalidArgs("limit"); if (!isPositiveInt(windowSeconds, 1)) invalidArgs("window"); if ((windowSeconds as number) > RATE_LIMIT_MAX_WINDOW_SECONDS) invalidArgs("window"); }
function assertRateLimitScope(scope: unknown): asserts scope is RateLimitScope { if (typeof scope !== "string" || !RATE_LIMIT_SCOPES.includes(scope as RateLimitScope)) invalidArgs("scope"); }
export function evaluateRateLimit(count: number, limit: number, windowSeconds: number): RateLimitResult { assertRateLimitBounds(limit, windowSeconds); if (!isPositiveInt(count, 0)) invalidArgs("count"); const allowed = count <= limit; return { allowed, count, remaining: Math.max(limit - count, 0), retryAfterSeconds: allowed ? 0 : Math.max(windowSeconds, 1) }; }
export async function rateLimitHit(request: RateLimitRequest): Promise<RateLimitResult> { const { scope, key, limit, windowSeconds } = request; assertRateLimitScope(scope); assertRateLimitBounds(limit, windowSeconds); if (typeof key !== "string" || key.trim().length === 0) invalidArgs("key"); try { const keyHash = await rateLimitKeyHash(scope, key); const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data, error } = await supabaseAdmin.rpc("rate_limit_hit", { _scope: scope, _key_hash: keyHash, _limit: limit, _window_seconds: windowSeconds }); if (error) throw error; const row = Array.isArray(data) ? data[0] : data; if (!row) throw new Error("rate_limit_hit returned no row"); return { allowed: Boolean(row.allowed), count: Number(row.current_count), remaining: Number(row.remaining), retryAfterSeconds: Number(row.retry_after_seconds) }; } catch (error) { console.error(`[protebe] rateLimitHit/${scope}: ${error instanceof Error ? error.message : error}`); throw new Error("rate limit unavailable"); } }
export async function rateLimitCleanup(): Promise<number> { try { const { supabaseAdmin } = await import("@/integrations/supabase/client.server"); const { data, error } = await supabaseAdmin.rpc("rate_limit_cleanup"); if (error) throw error; return Number(data ?? 0); } catch (error) { console.error(`[protebe] rateLimitCleanup: ${error instanceof Error ? error.message : error}`); return 0; } }