/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as KalendarRouteImport } from './routes/kalendar'
import { Route as NastaveniRouteImport } from './routes/nastaveni'
import { Route as VzkazyRouteImport } from './routes/vzkazy'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'
import { Route as ApiPublicCalendarKeyRouteImport } from './routes/api/public/calendar/$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const KalendarRoute = KalendarRouteImport.update({
  id: '/kalendar',
  path: '/kalendar',
  getParentRoute: () => rootRouteImport,
} as any)
const NastaveniRoute = NastaveniRouteImport.update({
  id: '/nastaveni',
  path: '/nastaveni',
  getParentRoute: () => rootRouteImport,
} as any)
const VzkazyRoute = VzkazyRouteImport.update({
  id: '/vzkazy',
  path: '/vzkazy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarKeyRoute = ApiPublicCalendarKeyRouteImport.update({
  id: '/api/public/calendar/$key',
  path: '/api/public/calendar/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galerie': typeof GalerieRoute
  '/kalendar': typeof KalendarRoute
  '/nastaveni': typeof NastaveniRoute
  '/vzkazy': typeof VzkazyRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/calendar/$key': typeof ApiPublicCalendarKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galerie': typeof GalerieRoute
  '/kalendar': typeof KalendarRoute
  '/nastaveni': typeof NastaveniRoute
  '/vzkazy': typeof VzkazyRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/calendar/$key': typeof ApiPublicCalendarKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galerie': typeof GalerieRoute
  '/kalendar': typeof KalendarRoute
  '/nastaveni': typeof NastaveniRoute
  '/vzkazy': typeof VzkazyRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/calendar/$key': typeof ApiPublicCalendarKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galerie'
    | '/kalendar'
    | '/nastaveni'
    | '/vzkazy'
    | '/api/public/upload'
    | '/api/public/calendar/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galerie'
    | '/kalendar'
    | '/nastaveni'
    | '/vzkazy'
    | '/api/public/upload'
    | '/api/public/calendar/$key'
  id:
    | '__root__'
    | '/'
    | '/galerie'
    | '/kalendar'
    | '/nastaveni'
    | '/vzkazy'
    | '/api/public/upload'
    | '/api/public/calendar/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalerieRoute: typeof GalerieRoute
  KalendarRoute: typeof KalendarRoute
  NastaveniRoute: typeof NastaveniRoute
  VzkazyRoute: typeof VzkazyRoute
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
  ApiPublicCalendarKeyRoute: typeof ApiPublicCalendarKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalendar': {
      id: '/kalendar'
      path: '/kalendar'
      fullPath: '/kalendar'
      preLoaderRoute: typeof KalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nastaveni': {
      id: '/nastaveni'
      path: '/nastaveni'
      fullPath: '/nastaveni'
      preLoaderRoute: typeof NastaveniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vzkazy': {
      id: '/vzkazy'
      path: '/vzkazy'
      fullPath: '/vzkazy'
      preLoaderRoute: typeof VzkazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$key': {
      id: '/api/public/calendar/$key'
      path: '/api/public/calendar/$key'
      fullPath: '/api/public/calendar/$key'
      preLoaderRoute: typeof ApiPublicCalendarKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalerieRoute: GalerieRoute,
  KalendarRoute: KalendarRoute,
  NastaveniRoute: NastaveniRoute,
  VzkazyRoute: VzkazyRoute,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
  ApiPublicCalendarKeyRoute: ApiPublicCalendarKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
