import { describe, expect, it } from "vitest";
import { czDays, formatCzechDate, formatCzechDateTime, loveDuration, timeOfDayGreeting, toVocativeCz } from "@/lib/cz";

describe("formatCzechDate", () => {
  it("formats an ISO date with the Czech genitive month", () => { expect(formatCzechDate("2024-01-09")).toBe("9. ledna 2024"); expect(formatCzechDate("2023-12-31")).toBe("31. prosince 2023"); expect(formatCzechDate("2020-05-01")).toBe("1. května 2020"); });
  it("returns the raw input when it is not a usable date", () => { expect(formatCzechDate("")).toBe(""); expect(formatCzechDate("nonsense")).toBe("nonsense"); expect(formatCzechDate("0000-00-00")).toBe("0000-00-00"); });
});
describe("formatCzechDateTime", () => { it("includes day, Czech month, year and a time separated by a middot", () => { const out=formatCzechDateTime("2024-03-05T08:30:00Z"); expect(out).toContain("března 2024"); expect(out).toContain("·"); expect(out).toMatch(/\d{1,2}[:.]\d{2}/); }); });
describe("czDays", () => { it("uses the three Czech plural forms", () => { expect(czDays(1)).toBe("1 den"); expect(czDays(2)).toBe("2 dny"); expect(czDays(4)).toBe("4 dny"); expect(czDays(5)).toBe("5 dní"); expect(czDays(0)).toBe("0 dní"); expect(czDays(11)).toBe("11 dní"); expect(czDays(101)).toBe("101 dní"); }); });
describe("loveDuration", () => { const anniversary="2024-01-01"; it("counts whole days since the anniversary",()=>{const r=loveDuration(anniversary,new Date("2024-01-11T00:00:00Z"));expect(r.days).toBe(10);expect(r.future).toBe(false);}); it("splits the remainder into hours, minutes and seconds",()=>{const r=loveDuration(anniversary,new Date("2024-01-02T03:04:05Z"));expect(r.days).toBe(1);expect(r.hours).toBe(3);expect(r.minutes).toBe(4);expect(r.seconds).toBe(5);}); it("reports years and months as calendar deltas",()=>{const r=loveDuration(anniversary,new Date("2026-03-15T00:00:00Z"));expect(r.years).toBe(2);expect(r.months).toBe(2);}); it("borrows a year when the month delta is negative",()=>{const r=loveDuration("2024-11-01",new Date("2025-02-01T00:00:00Z"));expect(r.years).toBe(0);expect(r.months).toBe(3);}); it("marks a future anniversary",()=>{const r=loveDuration("2030-06-01",new Date("2026-01-01T00:00:00Z"));expect(r.future).toBe(true);expect(r.years).toBe(0);}); });
describe("toVocativeCz",()=>{it("turns an -a feminine name into vocative",()=>{expect(toVocativeCz("Tereza")).toBe("Terezo");expect(toVocativeCz("Anna")).toBe("Anno");});it("leaves other endings untouched",()=>{expect(toVocativeCz("  Petr  ")).toBe("Petr");});});
describe("timeOfDayGreeting",()=>{const at=(hour:number)=>timeOfDayGreeting(new Date(2024,0,1,hour));it("covers bands",()=>{expect(at(0)).toBe("Něžná noc");expect(at(5)).toBe("Tiché ráno");expect(at(11)).toBe("Den s tebou");expect(at(17)).toBe("Zlatý večer");expect(at(22)).toBe("Tichá noc");});});